# Generated by Django 5.2.6 on 2025-10-26 10:31

import django.db.models.deletion
import valves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('oracle_code', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to=valves.models.get_maintenance_image_upload_path, verbose_name='Before Image')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to=valves.models.get_maintenance_image_upload_path, verbose_name='After Image')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('part_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartCode',
            fields=[
                ('part_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('sap_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('oracle_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_co', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valves.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('maintenance_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.maintenancehistory')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.partcode')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.sparepart')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valves.technician'),
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('valve_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('drawing_link', models.URLField(blank=True, max_length=500, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shut_off_pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('power_failure_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('body_style', models.CharField(blank=True, max_length=255, null=True)),
                ('required_travel_angle', models.CharField(blank=True, max_length=255, null=True)),
                ('bench_range', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valves.factory')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valves.manufacturer')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valves.valvestatus')),
                ('valve_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valves.valvetype')),
            ],
        ),
        migrations.CreateModel(
            name='Shutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valves.factory')),
                ('valves', models.ManyToManyField(to='valves.valve')),
            ],
        ),
        migrations.AddField(
            model_name='partcode',
            name='associated_valves',
            field=models.ManyToManyField(blank=True, to='valves.valve'),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='valve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.valve'),
        ),
        migrations.CreateModel(
            name='ValveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=valves.models.get_valve_image_upload_path, verbose_name='Image')),
                ('category', models.CharField(choices=[('Valves_Specs', 'Valve Specs'), ('P&ID', 'P&ID'), ('Maintenance_Reports', 'Maintenance Reports')], default='Valves_Specs', max_length=100, verbose_name='Image Category')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('valve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='valves.valve')),
            ],
        ),
    ]
