# Generated by Django 5.2.6 on 2025-09-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('technician_name', models.CharField(max_length=255)),
                ('maintenance_date', models.DateField()),
                ('before_image', models.ImageField(upload_to='maintenance_images/')),
                ('after_image', models.ImageField(upload_to='maintenance_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('part_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('valve_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('drawing_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartCode',
            fields=[
                ('code_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('maintenance_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.maintenancehistory')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.partcode')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.sparepart')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='valve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valves.valve'),
        ),
    ]
