# Generated by Django 5.2.6 on 2025-11-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehistory',
            name='valve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='valves.valve'),
        ),
        migrations.AlterField(
            model_name='partcode',
            name='associated_valves',
            field=models.ManyToManyField(blank=True, related_name='part_codes', to='valves.valve'),
        ),
    ]
