# Generated by Django 5.2.6 on 2025-12-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0003_maintenancehistory_maintenance_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='maintenance_activities',
        ),
    ]
