# Generated by Django 5.2.6 on 2025-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0004_remove_maintenancehistory_maintenance_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehistory',
            name='maintenance_activities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
