# Generated by Django 5.2.6 on 2026-04-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0005_maintenancehistory_maintenance_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='butterfly_shaft_mat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='leakage_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='packing_mat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='plug_stem_mat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='seat_diameter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='seat_guide_mat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='trim_coating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
