# Generated by Django 5.2.6 on 2026-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0006_valve_butterfly_shaft_mat_valve_leakage_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepart',
            name='quantity_used',
            field=models.FloatField(default=1.0),
        ),
    ]
