# Generated by Django 5.2.6 on 2026-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0007_maintenancepart_quantity_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehistory',
            name='pressure_test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='testing_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
