# Generated by Django 5.2.6 on 2026-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0008_maintenancehistory_pressure_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepart',
            name='associated_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
