# Generated by Django 5.2.6 on 2026-05-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0009_maintenancepart_associated_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepart',
            name='entered_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancepart',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valves.partcode'),
        ),
        migrations.AlterField(
            model_name='maintenancepart',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valves.sparepart'),
        ),
    ]
