# Generated by Django 5.2.6 on 2026-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0010_maintenancepart_entered_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehistory',
            name='is_shutdown',
            field=models.BooleanField(default=False, verbose_name='Shutdown'),
        ),
    ]
